# Generated by Django 4.1.1 on 2022-10-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VacunaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('dosis_N', models.IntegerField()),
                ('tipo_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.tipovacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('correo_electronico', models.CharField(max_length=70)),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='date published')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.BooleanField()),
                ('vacunas', models.ManyToManyField(to='vacunas.vacunaempleado')),
            ],
        ),
    ]
