# Generated by Django 4.1.1 on 2022-10-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunaempleado',
            name='marca',
        ),
    ]
