# Generated by Django 4.1.1 on 2022-10-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0002_remove_vacunaempleado_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.TextField(max_length=10),
        ),
    ]
