# Generated by Django 4.1.1 on 2022-10-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0003_empleado_vacunado_alter_empleado_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='vacunas',
            field=models.ManyToManyField(null=True, to='vacunas.vacunaempleado'),
        ),
    ]
