# Generated by Django 4.1.1 on 2022-10-02 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacunas', '0004_alter_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='vacunas',
            field=models.ManyToManyField(to='vacunas.vacunaempleado'),
        ),
    ]
