# Generated by Django 4.1.1 on 2022-10-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0006_remove_empleado_vacunas_vacunaempleado_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunaempleado',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacunas.empleado'),
        ),
    ]
