# Generated by Django 4.1.1 on 2022-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0007_alter_vacunaempleado_empleado'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('cedula',), name='unique cedula'),
        ),
    ]
