# Generated by Django 4.1.1 on 2022-10-03 17:28

from django.db import migrations, models
import vacunas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0008_empleado_unique cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, validators=[vacunas.models.verificar]),
        ),
    ]
